###################### Filebeat Configuration Example #########################

# This file is an example configuration file highlighting only the most common
# options. The filebeat.full.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

#=========================== Filebeat prospectors =============================

filebeat.prospectors:

# Each - is a prospector. Most options can be set at the prospector level, so
# you can use different prospectors for various configurations.
# Below are the prospector specific configurations.

# CONN_LOG
- input_type: log
  paths: 
    - "/usr/local/bro/logs/current/conn.log"
  
  fields:
    type: "bro-conn"
  fields_under_root: true

# DNS_LOG
- input_type: log
  paths:
    - "/usr/local/bro/logs/current/dns.log"
  fields:
    type: "bro-dns"
  fields_under_root: true

# HTTP_LOG
- input_type: log
  paths:
    - "/usr/local/bro/logs/current/http.log"
  fields:
    type: "bro-http"
  fields_under_root: true

# NOTICE_LOG
- input_type: log
  paths:
    - "/usr/local/bro/logs/current/notice.log"
  fields:
    type: "bro-notice"
  fields_under_root: true


#================================ Outputs =====================================
#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["172.16.100.123:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  # ssl.certificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"
